### ISSUE TITLE
Angular compatibility

### ISSUE THREAD

**Issue by dcop** [hypery2k/ngx-vis#115]
I'm trying to import the module into an angular 4 application, but I get the following error: 

`ERROR in Error: Metadata version mismatch for module ngx-vis.d.ts, found version 4, expected
3`

Reading here and there I see that this is something related to the supported angular version :
* angular 4 has metadata v3
* angular 5 has metadata v4

Now, checking [ngx-vis/ngx-vis.metadata.json](https://github.com/hypery2k/ngx-vis/blob/develop/ngx-vis.metadata.json) I see that module version is indeed 4.
Is this something intended? 

Thanks

**Comment by hypery2k** [comment]
no not actually. Any PR would be welcome

**Comment by dcop** [comment]
I'm kinda new to this stuff, so I googled and found (https://github.com/angular/angular/issues/19607)

I went ahead and downgraded to Angular 4 in package.json in my local build and module version is now 3. I don't know if this is the right way to do it or this thing will break something for newest Angular releases and if it's worth doing it.

What do you think?
