### ISSUE TITLE
storePositions request

### ISSUE THREAD

**Issue by anvial** [hypery2k/ngx-vis#141]
Can You add the **storePositions** method to the visNetworkService?

![image](https://user-images.githubusercontent.com/1950326/48833177-dd124800-ed8b-11e8-8ceb-e767396504b7.png)

see [here](http://visjs.org/docs/network/).

Thank You.

**Comment by hypery2k** [comment]
you can give `ngx-vis@2.0.0-feature-storePositions-141-2` a shot and report feedback here

**Comment by anvial** [comment]
Hi, 
Sorry for very late response... 6 month ago was curious about this package for angular. 

Now I use it in working project.

Is this issue already in release, or you still waiting for a feedback.

I'm really feel sorry, for such irresponsible behavior.

**Comment by hypery2k** [comment]
no problem. The feature is not yet merged.

So if it's working for you I'll add it to the next release

**Comment by anvial** [comment]
Yeap, this feature is interesting because it gives a convenient way to implement the animations. 

Btw, what about method 'setOptions' ? Is it already in release?

**Comment by hypery2k** [comment]
Version 2.2.0 is released: https://github.com/hypery2k/ngx-vis/releases/tag/v2.2.0
