### ISSUE TITLE
Can't Bind to [visNetwork]

### ISSUE THREAD

**Issue by queejie** [hypery2k/ngx-vis#186]
* [x ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/hypery2k/ngx-vis/master/CONTRIBUTING.md).

## What did you do?

ℹ Used demo code for network in my module.  

ℹ Expected to see graph and compile without errors.  

ℹ Received an error:
**Can't bind to 'visNetwork' since it isn't a known property of 'div'.** 
`            <div class="network-canvas"
                 [visNetwork]="visNetwork"
                 [visNetworkData]="visNetworkData"
                 [visNetworkOptions]="visNetworkOptions"
                 (initialized)="networkInitialized()">
            </div>
`

## Your Environment
Mac OS X
**Angular 7**
**NodeJS 11.10.0 and NPM 6.8.0:**

## Demo Project

![image](https://user-images.githubusercontent.com/1616827/53644277-321fee80-3c04-11e9-8a3e-537d951accea.png)

**Comment by hypery2k** [comment]
not able to reproduce. With [the demo app](https://github.com/hypery2k/ngx-vis/blob/develop/demo/demo.module.ts#L23) it's working for me.
