### ISSUE TITLE
"getBoundingBox" request

### ISSUE THREAD

**Issue by anvial** [hypery2k/ngx-vis#228]
Hi again, 

Can I ask to add support of 'getBoundingBox' method in VisNetworksService? 

Thank You!

**Comment by hypery2k** [comment]
you can give `ngx-vis@2.2.0-feature-getBoundingBox-228-2` a shot

**Comment by anvial** [comment]
Thx! Check It, 

![image](https://user-images.githubusercontent.com/1950326/58627933-14d0ee00-82e1-11e9-89f8-9440fe4636ce.png)

work like a charm =)

**Comment by hypery2k** [comment]
glad to here

**Comment by hypery2k** [comment]
Released as version 2.3.0: https://github.com/hypery2k/ngx-vis/releases/tag/v2.3.0
