### ISSUE TITLE
Update dependency @types/vis

### ISSUE THREAD

**Issue by Yasti4** [hypery2k/ngx-vis#232]
## Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository

## Current Behavior

Hi, I downloaded the latest version, with the command 
```
npm install ngx-vis@lastest
```

The version that has been installed is: **ngx-vis 2.3.0**

I was trying to use the property **widthConstraint**, but **not found** in the interface,
the dependency that has been installed is: 
"vis": "4.21.0",
@types/vis": "4.21.15"

I would **need the library to upgrade** to version:
**@types/vis": "4.21.16"**

* Angular version: 7.3.1

Sorry for the inconvenience and very good job 
Best regards!

```

**Comment by hypery2k** [comment]
thanks for the info, just released [2.3.1](https://github.com/hypery2k/ngx-vis/releases/tag/v2.3.1)
