### ISSUE TITLE
FeatureR: getNodeAt(pos)

### ISSUE THREAD

**Issue by PaulHindenberg** [hypery2k/ngx-vis#53]
**FeatureRequest**

## What did you do?

Tried calling the function getNodeAt(Pos) after the event "oncontext" to get the Node at a certain position. 
## What did you expect to happen?

Getting the Node
## What happened instead?

Method is not implemented 

## Your Environment

**Angular version:** 5.1.1
**NodeJS and NPM version:** 5.5.1

**Comment by hypery2k** [comment]
available in version 0.2.0
