### ISSUE TITLE
Manual zoom in and zoom out functionality missing

### ISSUE THREAD

**Issue by sarahm7** [hypery2k/ngx-vis#69]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/hypery2k/ngx-vis/master/CONTRIBUTING.md).

## What did you do?

I'm trying to use the moveTo implementation but it doesn't seem to work? and the VisNetworkService wrapper doesn't seem to have that method yet.

## What did you expect to happen?

Manually zoom in and zoom out via button click

## What happened instead?

Nothing happened.

## Your Environment

Angular CLI: 1.6.5
Node: 8.9.1
OS: win32 x64
Angular: 5.2.8
ngx-vis: 0.2.0

**Comment by hypery2k** [comment]
can you please post the exact code you're using? A snippet would be nice or maybe a demo project to reproduce the error

**Comment by PaulHindenberg** [comment]
@sarahm7 right, its currently not implemented into the wrapper. 
@hypery2k I just created PR #70 were I added some more methods into the network.service.ts. One of them is moveTo.

**Comment by hypery2k** [comment]
you can give „ngx-vis@0.2.0-develop-26“ a try

**Comment by sarahm7** [comment]
Thanks guys, it worked perfectly! Sorry i couldn't provide a snippet before.
