### ISSUE TITLE
VisNetworkService fails after NgOnDestroy

### ISSUE THREAD

**Issue by sarahm7** [hypery2k/ngx-vis#77]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/hypery2k/ngx-vis/master/CONTRIBUTING.md).

## What did you do?

I'm trying to use the getConnectedNodes method through the visNetworkService. 

## What happened instead?

This only happens when you change routes in Angular through the router-outlet then going back to the network view page, i get below error.

![image](https://user-images.githubusercontent.com/27810542/37815603-738cd9e0-2eaa-11e8-88dc-510f15963710.png)

On the first click it fails, then when i click again it suddenly works. Any idea?

Code:

html => 
```
<div #treeview id="mynetwork" class="network-canvas h-100 d-block" [visNetwork]="visNetwork" [visNetworkData]="visNetworkData" [visNetworkOptions]="visNetworkOptions"
    (initialized)="networkInitialized()"></div>
```

typescript =>
```
public networkInitialized(): void {
this.visNetwork = 'mynetwork';
this.visNetworkService.on(this.visNetwork, 'click');

this.visNetworkService.click
      .subscribe((eventData: PropertiesExt[]) => {
      const selectedNode: string = this.setupService.getSelectedNode(eventData);
      const connectedNodes = this.visNetworkService.getConnectedNodes(this.visNetwork, selectedNode);
});
}

public ngOnDestroy(): void {
    this.visNetworkService.destroy(this.visNetwork);
    this.visNetwork = null;
}

```
## Your Environment

Angular CLI: 1.6.5
Node: 8.9.1
OS: win32 x64
Angular: 5.2.8
ngx-vis: 0.2.0

**Comment by hypery2k** [comment]
does it work now with 0.3.1?

**Comment by hypery2k** [comment]
close due to no response
